Changed tomb error code checks

diff --git a/sandstart b/sandstart
--- a/sandstart
+++ b/sandstart
@@ -70,13 +70,14 @@ if [ "$?" -eq 1 ]; then
 	exit 1
 fi
 
-"${TOMBIN}" list "`basename ${TFILE}`" &> /dev/null
-
-if [ $? -eq 1 ]; then
+"${TOMBIN}" list "`basename ${TFILE}`" &>/dev/null
+if [ "$?" -eq 0 ]; then
 	"${TOMBIN}" open "${TFILE}"
-fi
-
-if [ $? -eq 1 ]; then
+	if [ "$?" -eq 1 ]; then
+		exit 1
+	fi
+else
+	echo "Error: cannot find $TFILE. Please run '$0 info' for more informations"
 	exit 1
 fi
 
