Added 'sudo' checks

diff --git a/sandstart b/sandstart
--- a/sandstart
+++ b/sandstart
@@ -9,6 +9,7 @@ KFILE="${HOME}/myshinytomb.key"
 BIN="${PWD}/bin"
 SANDTOMB="${BIN}/sandtomb"
 TOMBIN="${BIN}/tomb"
+SUDO="`which sudo`"
 
 function usage() {
 	echo "Usage:"
@@ -70,6 +71,11 @@ if [ "$?" -eq 1 ]; then
 	exit 1
 fi
 
+if ! [ "${SUDO}" ] || ! [ -e "${SUDO}" ]; then
+	echo "Error: 'sudo' not found. Please install it."
+	exit 1
+fi
+
 "${TOMBIN}" list "`basename ${TFILE}`" &>/dev/null
 if [ "$?" -eq 0 ]; then
 	"${TOMBIN}" open "${TFILE}"
@@ -83,4 +89,4 @@ fi
 
 TOMBMOUNT="${MNTP}/"`basename ${TFILE}`""
 
-sudo "${SANDTOMB}" --mountpoint "${TOMBMOUNT}" --profile "${WHAT}" "${WHAT}"
+"${SUDO}" "${SANDTOMB}" --mountpoint "${TOMBMOUNT}" --profile "${WHAT}" "${WHAT}"
